# Generated by Django 3.2 on 2023-08-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20230815_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='numero_pedido',
            new_name='codigo',
        ),
    ]
